### PR TITLE
Fix race condition with multiple inventories

### LINKED ISSUE #38: Possible race condition between multiple ansible_playbook resources?
Hello,

I read the code of the `ansible_playbook` resource and I don’t understand this line:
https://github.com/ansible/terraform-provider-ansible/blob/c3f22e32972f1c5838b0fe250e90e045cb7c1ef6/provider/resource_playbook.go#L474
Why can’t we just use the `tempInventoryFile` variable? Also, doesn’t it open the door to race conditions between multiple `ansible_playbook` (taking into account inventory files of each others)?

### PR DESCRIPTION
**Pull request by fbjerggaard**
I don't see why we are getting all the temp inventory files existing on disk since we are only ever generating 1. This PR fixes that by only using the one we just generated

Fixes #38

### CODE REVIEW

**Comment by rwblokzijl** [comment]
@anazobec @gravesm would it be possible to merge this? For us this has lead to behaviour were the playbook was run on an inventroy file from a previous failed terraform run, and therefore on the wrong host.

File: provider/resource_playbook.go [hunk 1]
```diff
@@ -470,23 +470,14 @@ func resourcePlaybookUpdate(data *schema.ResourceData, meta interface{}) error {
 
 	log.Printf("Temp Inventory File: %s", tempInventoryFile)
 
-	// Get all available temp inventories and pass them as args
-	inventories := providerutils.GetAllInventories(inventoryFileNamePrefix)
-
 	log.Print("[INVENTORIES]:")
 	log.Print(inventories)
```
Comment (anazobec) [inline provider/resource_playbook.go:474]: Hi, thank you for contributing :)
I will approve and merge this PR once all the tests pass. I approved workflow (tests) run for this PR and both of the tests failed. I think removing the lines I've marked should make the tests pass.

**Review by anazobec — COMMENTED** [review]
Hi thank you for contributing :)
Just a few small changes are needed before approval and merge.

File: provider/resource_playbook.go (hunk 1 above)
Comment (fbjerggaard) [reply provider/resource_playbook.go]: Done :)
